### ISSUE TITLE
[BeyondImporter] Alert is not increasing Initiative

### ISSUE THREAD

**Issue by Andargor** [RobinKuiper/Roll20APIScripts#33]
The Alert feat is not giving +5 to Initiative

**Comment by derammo** [comment]
NOTE to implementer:  Roll20 applies "Ability Checks" bonus to initiative, which is why we don't have to import the "initiative" bonus modifier for "Luck Stone" for example.  We need to be careful when adding support for initiative bonus to avoid double incrementing for items that have both ability checks and initiative bonus in Beyond.

**Comment by sillvva** [comment]
Confirmed working

**Comment by derammo** [comment]
released as 0.4.0 to master
